
# html lang
language:

# main menu navigation
menu:
  Home: /
  Archives: /archives
  About: /about

# feed，rss订阅
feed:
  type: atom
  path: atom.xml
  limit: 20

# 第三方网站链接，目前只有github和新浪微博
github: https://github.com/yawuling
sina: http://weibo.com/2829733683/profile?topnav=1&wvr=6

# About页面参数，需要在博客根目录执行“hexo new page "about"”
# 要添加链接，直接增添 'url' 字段
about:
  photo: /image/person.jpg
  items:
    - label: name
      title: 钟志杰
    - label: nickname
      title: 涯无凌
    - label: E-mail
      title: zhijie_csu@163.com
    - label: Github
      title: https://github.com/yawuling
      url: https://github.com/yawuling

# 网站icon设置，网站顶部背景图
favicon: /favicon.ico
bg: /image/bg.jpg

# stylesheets loaded in the <head>
stylesheets:
- /css/Ani.css
- /css/github-markdown.css
- /css/highlight.css
- /css/jquery.fancybox.min.css

# scripts loaded in the end of the body
scripts:
- /js/Ani.js
- /js/jquery-3.2.1.min.js
- /js/search.js
- /js/jquery.fancybox.min.js

# toolbar setting
toolbar: right
category_show_count: true
tag_show_count: true
archive_show_count: true

# toolbar-widgets
widgets:
- search
- toc
- recent_posts
- category
- tag
- archive
- tagcloud

# post setting
copyright: '转载请注明出处，谢谢！'  # 转载文字设置
tip:   # 是否开启打赏
  wepay: /image/wepay.JPG      # 微信支付二维码
  alipay: /image/alipay.JPG    # 支付宝二维码
  label: '您的支持将鼓励我继续创作！'  # 打赏文字设置

# totop
totop: true

# 插件设置
# 百度统计
baidu_analytics: 
# 不蒜子
busuanzi: true
# 畅言
changyan:
  appId: 
  conf: 
# 百度分享服务
share: true
