categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
Prev: Prev
Next: Next
comment: Comments
archive_a: Archives
page: Page %d
recent_posts: Recent Posts
toc: Toc
newer: Newer
older: Older
share: Share
powered_by: Powered by
rss_feed: RSS Feed
category: Category
tag: Tag
Home: Home
Archives: Archives
About: About
Rss: Rss
readmore: Readmore
name: Name
nickname: Nickname
E-mail: E-mail
Github: Github
